### ISSUE TITLE
Vereinheitlichung des icon Speicherorts

### ISSUE THREAD

**Issue by Kolophonium0** [zpd-digital-editions/narragonia-latina-oxygen#6]
Momentan gibt es sowohl unter /resources/icons einen Button Icon Speicherort, als auch unter /Button Images. Bitte alles auf /resources/icons wechseln.

**Comment by jroth16** [comment]
Die Bilder für die Icons sind alle unter resources/icons gespeichert. Die Icons, die durch das Verschieben der Dateien nicht mehr in Oxygen Author sichtbar waren, wurden wieder eingefügt.
